package com.DCS.AIEngineerDCSapp;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.data.jpa.repository.JpaRepository;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
public class AiEngineerDcsAppApplication {

	public static void main(String[] args) {
		SpringApplication.run(AiEngineerDcsAppApplication.class, args);
	}

}
